sudo: required

services:
    - docker

env:
    global:
        - DOCKER_COMPOSE_VERSION=1.17.0

before_install:
    - sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

before_script:
    - docker-compose up -d --build

script:
    - docker-compose run users-service python manage.py test

after_script:
    - docker-compose down
